#!/bin/sh
# Install necessary packages
apk add --no-cache openssh bash shadow sudo

# Clean up APK cache to reduce container size
rm -rf /var/cache/apk/*

# Generate host SSH keys
ssh-keygen -A

# Setup user with a password
echo "root:root" | chpasswd
adduser -D -s /bin/bash user
echo "user:password" | chpasswd

# Update SSH configuration to allow password authentication
sed -i '/^PasswordAuthentication/s/no/yes/' /etc/ssh/sshd_config
sed -i '/^#PermitRootLogin/s/#PermitRootLogin/PermitRootLogin/' /etc/ssh/sshd_config
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config

# Add user to sudoers
echo 'user ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/user

# Ensure permissions are correct
chown -R user:user /home/user
