#!/usr/bin/env zsh

SNOWSQL_VERSION="1.2.32"
SNOWSQL_ARCH="x86_64"
SNOWSQL_FILE="snowsql-${SNOWSQL_VERSION}-linux_${SNOWSQL_ARCH}.bash"
SNOWSQL_DOWNLOAD_URL="https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_${SNOWSQL_ARCH}/${SNOWSQL_FILE}"

# Download SnowSQL
curl -k -L -o ${SNOWSQL_FILE} ${SNOWSQL_DOWNLOAD_URL}
chmod +x ${SNOWSQL_FILE}

# Make sure ~/bin exists and can be written to
mkdir -p ~/bin
chmod 755 ~/bin

# Create a profile file (if it doesn't exist)
# This is where the SnowSQL installer will write the configuration
touch ~/.profile

# Run the installer
SNOWSQL_DEST=~/bin SNOWSQL_LOGIN_SHELL=~/.profile bash ${SNOWSQL_FILE} -y
